### ISSUE TITLE
HOTFIX: Fix test cases

### ISSUE THREAD

**Issue by SamuelCarroll** [activecm/ipfix-rita#77]
With recent changes to master, we didn't ensure that the test cases didn't break. Some have been fixed but it appears some changes have broken other tests.

```
flow_deserializer_test.go:16:1: expected declaration, found ')'
flow_deserializer_test.go:45:46: string literal not terminated
flow_deserializer_test.go:46:9: string literal not terminated
flow_deserializer_test.go:78:2: expected declaration, found 'IDENT' require
flow_deserializer_test.go:118:2: expected declaration, found 'IDENT' require
flow_deserializer_test.go:170:2: expected declaration, found 'IDENT' require
flow_deserializer_test.go:177:2: expected declaration, found 'IDENT' require
flow_deserializer_test.go:266:2: expected declaration, found 'IDENT' require
FAIL .../ipfix-rita/converter/input/mgologstash [setup failed]

[more tests]

panic: Error response from daemon: No such container: [container number]

go routine 1 [running]:
github.com/activecm/ipfix-rita/converter/integrationtest.NewMongoDBContainerFixture.func2([addresses])
    .../ipfix-rita/converter/integrationtest/mongo.go
    .../ipfix-rita/converter/integrationtest.(*FixtureManager).EndTestPackage([address])
    .../ipfix-rita/converter/integrationtest/fixtures.go:174 +0x2bd
    .../ipfix-rita/converter/output/rita/buffered_test.TestMain ([address])
    .../ipfix-rita/converter/output/rita/buffered/main_test.go:53 +0x366
main.main()
    .../ipfix-rita/converter/output/rita/buffered/_test/_testmain.go:48 + 0xdb
exit status 2
FAIL .../ipfix-rita/converter/output/rita/buffered

[more tests]

panic error response from daemon: No such container: [container id]

goroutine 1 [running]:
.../ipfix-rita/converter/integrationtest.NewMongoDBContainerFixture.func2([addresses])
    .../ipfix-rita/converter/integrationtest/mongo.go:32 +0x215
.../ipfix-rita/converter/integrationtest.(*FixtureManager).EndTestPackage([address])
    .../ipfix-rita/converter/integrationtest/fixtures.go:174 +0x2bd
.../ipfix-rita/converter/output/rita/streaming/dates_test.TestMain([address])
    .../ipfix-rita/converter/output/rita/streaming/dates/main_test.go:109 +0x40f
main.main()
    .../ipfix-rita/converter/output/rita/streaming/dates/_test/_testmain.go:62 +0xdb
exit status 2
FAIL     .../ipfix-rita/converter/output/rita/streaming/dates
```
<S>With this comes the question of having integration tests at this level.</S> I need to double check with Melissa

**Comment by Zalgo2462** [comment]
We'll have to meet up over to work on the Docker fix. The other errors seem to be fixed by PR #78.
